### ISSUE TITLE
Crunchyroll and FUNimation not working (Might be doing it wrong)

### ISSUE THREAD

**Issue by dapikmincoder** [Xonshiz/anime-dl#81] opened 2019-02-22 02:27 UTC
So I downloaded this anime-dl and, yes, I made sure I have FFmpeg, node.js, mkvmerge, and Python ALL installed and ALL have paths set in Command prompt. So I tried to download from FUNimation and kept getting an error saying 'NoneType' object has no attribute 'group'. Now I saw a year old post saying FUNimation wasn't working and is in development. Don't know if that's still the case but just in case I checked to see if I can download from Crunchyroll. And yes, I have premiums for both. When I tried Crunchyroll I got the error "Could not extract language from the URL". If it makes any difference I tried messing around with all sorts of things such as changing the username and password to see if I got it wrong, trying different resolutions and languages, etc.
Now as requested, I will post the command prompt text and error logs with the usernames and passwords blacked out.

Microsoft Windows [Version 10.0.17134.590]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\⬛>cd Documents

C:\Users\⬛\Documents>cd anime-dl-master

C:\Users\⬛\Documents\anime-dl-master>cd anime_dl

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "1080p" -v
This lang :  Japanese
Traceback (most recent call last):
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 18, in <module>
    class main():
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 75, in main
    logger=logger, episode_range=args.range)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\AnimeDL.py", line 46, in __init__
    sites.funimation.Funimation(url[0], username, password, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 16, in __init__
    self.singleEpisode(url, self.cookies, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 71, in singleEpisode
    playerID = str(re.search(r'\"\/player\/(.*?)\"\>', str(fetchConnect)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\⬛\Documents\anime-dl-master\anime_dl>anime-dl.exe -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "1080p" -v
'anime-dl.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "720p" -v
This lang :  Japanese
Traceback (most recent call last):
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 18, in <module>
    class main():
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 75, in main
    logger=logger, episode_range=args.range)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\AnimeDL.py", line 46, in __init__
    sites.funimation.Funimation(url[0], username, password, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 16, in __init__
    self.singleEpisode(url, self.cookies, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 71, in singleEpisode
    playerID = str(re.search(r'\"\/player\/(.*?)\"\>', str(fetchConnect)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "720p" -l dub -v
This lang :  dub
Traceback (most recent call last):
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 18, in <module>
    class main():
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 75, in main
    logger=logger, episode_range=args.range)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\AnimeDL.py", line 46, in __init__
    sites.funimation.Funimation(url[0], username, password, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 16, in __init__
    self.singleEpisode(url, self.cookies, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 71, in singleEpisode
    playerID = str(re.search(r'\"\/player\/(.*?)\"\>', str(fetchConnect)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.crunchyroll.com/one-piece/one-piece-episode-of-skypiea-episode-of-skypiea-776847" -u "⬛" -p "⬛" -r "1080p" -v
Could not extract the language from the URL

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.crunchyroll.com/one-piece/one-piece-episode-of-skypiea-episode-of-skypiea-776847" -u "⬛" -p "⬛" -r "1080p" -l "Japanese" -v
Could not extract the language from the URL

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "1080p" -l "Japanese" -v
This lang :  Japanese
Traceback (most recent call last):
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 18, in <module>
    class main():
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 75, in main
    logger=logger, episode_range=args.range)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\AnimeDL.py", line 46, in __init__
    sites.funimation.Funimation(url[0], username, password, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 16, in __init__
    self.singleEpisode(url, self.cookies, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 71, in singleEpisode
    playerID = str(re.search(r'\"\/player\/(.*?)\"\>', str(fetchConnect)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\⬛\Documents\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c" -u "⬛" -p "⬛" -r "1080p" -l "Japanese" -v
This lang :  Japanese
Traceback (most recent call last):
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 18, in <module>
    class main():
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\__main__.py", line 75, in main
    logger=logger, episode_range=args.range)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\AnimeDL.py", line 46, in __init__
    sites.funimation.Funimation(url[0], username, password, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 16, in __init__
    self.singleEpisode(url, self.cookies, resolution, language)
  File "C:\Users\⬛\Documents\anime-dl-master\anime_dl\sites\funimation.py", line 71, in singleEpisode
    playerID = str(re.search(r'\"\/player\/(.*?)\"\>', str(fetchConnect)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\⬛\Documents\anime-dl-master\anime_dl>

And now the error.log

DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['<https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c>'], language='Japanese', password=['⬛!'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=['⬛!'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 210
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=['⬛?'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 722
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=None, range='All', resolution=['720p'], skip=False, username=['⬛?'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=[' https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=None, range='All', resolution=['720p'], skip=False, username=['⬛?'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=None, range='All', resolution=['1080p'], skip=False, username=['⬛?'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=['⬛?'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 721
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language='Japanese', password=['⬛?'], range='All', resolution=['720p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 721
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language=['dub'], password=['⬛?'], range='All', resolution=['720p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=english HTTP/1.1" 200 722
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/one-piece/one-piece-episode-of-skypiea-episode-of-skypiea-776847'], language='Japanese', password=['⬛'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/one-piece/one-piece-episode-of-skypiea-episode-of-skypiea-776847'], language=['Japanese'], password=['⬛'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language=['Japanese'], password=['⬛'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 210
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.funimation.com/shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c'], language=['Japanese'], password=['⬛?'], range='All', resolution=['1080p'], skip=False, username=['⬛'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17134
DEBUG: Python Version : 3.7.2 (32bit)
DEBUG: Starting new HTTPS connection (1): prod-api-funimationnow.dadcdigital.com:443
DEBUG: https://prod-api-funimationnow.dadcdigital.com:443 "POST /api/auth/login/ HTTP/1.1" 401 None
DEBUG: Starting new HTTPS connection (1): www.funimation.com:443
DEBUG: https://www.funimation.com:443 "GET /shows/one-piece/time-limit-the-human-auction-begins/?qid=83bced2a10ad932c?lang=japanese HTTP/1.1" 200 829

**Comment by dapikmincoder** [comment] 2019-02-22 18:26
Edit: I realized I did not have the latest version and had to get the one from https://github.com/Xonshiz/anime-dl/releases/tag/2019.01.27 . However after doing this I got the exact same errors.

**Comment by Xonshiz** [comment] 2019-02-23 06:42
Yes, this is a known issue and we've had discussion regarding it. Try adding "/en-US" at the end of the URL. Follow #77 for this. I'll be pushing an updated .exe that includes this fix. So, closing this for now, as it is a duplicate of #77 .

And as for Funimation, it won't work, as I have not gotten time to look into how to download content from there after they updated their APIs and I do not have an account to check for the same. There's already a request pending for FUnimation inclusion as well.

**Closed by Xonshiz** 2019-02-23 06:42 UTC
